### PR TITLE
Removed merge conflict markers due to #37 pull request

### PR DESCRIPTION
**Pull request by paraschetal**
Small change for installer.py to work.

### CODE REVIEW

**Comment by Pratik151** [comment]
Hello @paraschetal 

You will need to remove this [line](https://github.com/paraschetal/OWASP-ZSC/blob/master/installer.py#L53). You can see that conflict is for that line so you need to remove one of the two lines. You can see more about merge conflicts [here](https://help.github.com/articles/resolving-a-merge-conflict-from-the-command-line/). In current [installer.py](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/installer.py) remove line 52-55 and 57.

Regards,
Pratik Patel

**Comment by paraschetal** [comment]
thanks @Pratik151 
I thought that both the error messages have to be displayed, so I kept them as such. Now I've removed the older message.

**Comment by Pratik151** [comment]
@paraschetal  I think you removed wrong line in your latest commit. You need to have this [line](https://github.com/Ali-Razmjoo/OWASP-ZSC/blob/master/installer.py#L56)

**Comment by paraschetal** [comment]
thanks a lot @Pratik151. I hope it's right now.

**Comment by Ali-Razmjoo** [comment]
Thanks for fixation.

**Pull request merged**
